# This module defines
# MYGUI_LIBRARIES, MYGUI_OPENGL_LIBRARIES, MYGUI_OGRE_LIBRARIES
# MYGUI_FOUND, etc.
# MYGUI_INCLUDE_DIR, where to find the headers

SET(MYGUI_DEBUG_POSTFIX "_d" CACHE STRING "add a postfix for MyGUI Debug library, usually _d on windows")

FIND_PATH(MYGUI_INCLUDE_DIR MYGUI/MyGUI_Prerequest.h)

if(MYGUI_INCLUDE_DIR)
	file(READ ${MYGUI_INCLUDE_DIR}/MYGUI/MyGUI_Prerequest.h TEMP_H)
	string(REGEX MATCH "#define[ ]+MYGUI_VERSION_MAJOR[ ]+[0-9]+" MYGUI_VERSION_MAJOR ${TEMP_H})
	string(REGEX MATCH "#define[ ]+MYGUI_VERSION_MINOR[ ]+[0-9]+" MYGUI_VERSION_MINOR ${TEMP_H})
	string(REGEX MATCH "#define[ ]+MYGUI_VERSION_PATCH[ ]+[0-9]+" MYGUI_VERSION_PATCH ${TEMP_H})
	string(REGEX REPLACE "^[^0-9]+([0-9]+)$" "\\1" MYGUI_VERSION_MAJOR ${MYGUI_VERSION_MAJOR})
	string(REGEX REPLACE "^[^0-9]+([0-9]+)$" "\\1" MYGUI_VERSION_MINOR ${MYGUI_VERSION_MINOR})
	string(REGEX REPLACE "^[^0-9]+([0-9]+)$" "\\1" MYGUI_VERSION_PATCH ${MYGUI_VERSION_PATCH})
	if(MYGUI_VERSION_MAJOR
		AND MYGUI_VERSION_MINOR
		AND MYGUI_VERSION_PATCH
	)
		set(MYGUI_VERSION "${MYGUI_VERSION_MAJOR}.${MYGUI_VERSION_MINOR}.${MYGUI_VERSION_PATCH}")
	endif()
endif()

MACRO(FIND_MYGUI_LIBRARY MYLIBRAR MYLIBRARYNAME)

    FIND_LIBRARY("${MYLIBRAR}Y_DEBUG"
        NAMES "${MYLIBRARYNAME}${MYGUI_DEBUG_POSTFIX}"
    )

    FIND_LIBRARY("${MYLIBRAR}Y_RELEASE"
        NAMES "${MYLIBRARYNAME}"
    )

    IF( NOT ${MYLIBRAR}Y_DEBUG)
        IF(${MYLIBRAR}Y_RELEASE)
            SET(${MYLIBRAR}Y_DEBUG ${${MYLIBRAR}Y_RELEASE})
        ENDIF()
    ELSE()
        IF( NOT ${MYLIBRA}Y_RELEASE )
            SET(${MYLIBRA}Y_RELEASE ${${MYLIBRAR}Y_DEBUG} )
        ENDIF()
    ENDIF()
	
	set(${MYLIBRAR}IES debug ${${MYLIBRAR}Y_DEBUG} optimized ${${MYLIBRAR}Y_RELEASE})

ENDMACRO()

FIND_MYGUI_LIBRARY(MYGUI_LIBRAR MyGUIEngine)
FIND_MYGUI_LIBRARY(MYGUI_OPENGL_LIBRAR MyGUI.OpenGLPlatform)
#FIND_MYGUI_LIBRARY(MYGUI_OGRE_LIBRAR MyGUI.OgrePlatform)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MYGUI REQUIRED_VARS MYGUI_LIBRARIES MYGUI_INCLUDE_DIR VERSION_VAR MYGUI_VERSION)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MYGUI_OPENGL REQUIRED_VARS MYGUI_OPENGL_LIBRARIES)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(MYGUI_OGRE REQUIRED_VARS MYGUI_OGRE_LIBRARIES)
