# This module defines
# MYGUI_LIBRARIES, MYGUI_OPENGL_LIBRARIES, MYGUI_OGRE_LIBRARIES
# MYGUI_FOUND, etc.
# MYGUI_INCLUDE_DIR, where to find the headers

SET(MYGUI_DEBUG_POSTFIX "_d" CACHE STRING "add a postfix for MyGUI Debug library, usually _d on windows")

FIND_PATH(MYGUI_INCLUDE_DIR MYGUI/MyGUI.h)

MACRO(FIND_MYGUI_LIBRARY MYLIBRAR MYLIBRARYNAME)

    FIND_LIBRARY("${MYLIBRAR}Y_DEBUG"
        NAMES "${MYLIBRARYNAME}${MYGUI_DEBUG_POSTFIX}"
    )

    FIND_LIBRARY("${MYLIBRAR}Y_RELEASE"
        NAMES "${MYLIBRARYNAME}"
    )

    IF( NOT ${MYLIBRAR}Y_DEBUG)
        IF(${MYLIBRAR}Y_RELEASE)
            SET(${MYLIBRAR}Y_DEBUG ${${MYLIBRAR}Y_RELEASE})
        ENDIF()
    ELSE()
        IF( NOT ${MYLIBRA}Y_RELEASE )
            SET(${MYLIBRA}Y_RELEASE ${${MYLIBRAR}Y_DEBUG} )
        ENDIF()
    ENDIF()
	
	set(${MYLIBRAR}IES debug ${${MYLIBRAR}Y_DEBUG} optimized ${${MYLIBRAR}Y_RELEASE})

ENDMACRO()

FIND_MYGUI_LIBRARY(MYGUI_LIBRAR MyGUIEngine)
FIND_MYGUI_LIBRARY(MYGUI_OPENGL_LIBRAR MyGUI.OpenGLPlatform)
#FIND_MYGUI_LIBRARY(MYGUI_OGRE_LIBRAR MyGUI.OgrePlatform)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MYGUI REQUIRED_VARS MYGUI_LIBRARIES MYGUI_INCLUDE_DIR)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MYGUI_OPENGL REQUIRED_VARS MYGUI_OPENGL_LIBRARIES)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(MYGUI_OGRE REQUIRED_VARS MYGUI_OGRE_LIBRARIES)
